<?php

namespace Database\Seeders;

use App\Models\Img;
use App\Models\User;
use App\Models\Views;
use App\Models\ViewsType;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    use WithoutModelEvents;

    /**
     * Seed the application's database.
     */
    public function run(): void
    {
        // 建立測試使用者 (如果不不需要可註解掉)
        User::factory()->create([
            'name' => 'Test User',
            'email' => 'test@example.com',
        ]);

        ViewsType::insert([
            [
                'typeName' => '自然景觀',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'typeName' => '美食購物',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'typeName' => '體驗活動',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'typeName' => '歷史文化',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'typeName' => '國家公園',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'typeName' => '其他',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
        //60筆資料
        Img::insert([
            ['viewsId' => 1, 'imgSrc' => 'landscape (1).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 1, 'imgSrc' => 'landscape (2).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 1, 'imgSrc' => 'landscape (3).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 2, 'imgSrc' => 'landscape (4).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 2, 'imgSrc' => 'landscape (5).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 2, 'imgSrc' => 'landscape (6).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 3, 'imgSrc' => 'landscape (7).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 3, 'imgSrc' => 'landscape (8).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 3, 'imgSrc' => 'landscape (9).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 4, 'imgSrc' => 'landscape (10).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 4, 'imgSrc' => 'landscape (11).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 4, 'imgSrc' => 'landscape (12).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 5, 'imgSrc' => 'landscape (13).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 5, 'imgSrc' => 'landscape (14).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 5, 'imgSrc' => 'landscape (15).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 6, 'imgSrc' => 'landscape (16).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 6, 'imgSrc' => 'landscape (1).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 6, 'imgSrc' => 'landscape (2).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 7, 'imgSrc' => 'landscape (3).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 7, 'imgSrc' => 'landscape (4).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 7, 'imgSrc' => 'landscape (5).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 8, 'imgSrc' => 'landscape (6).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 8, 'imgSrc' => 'landscape (7).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 8, 'imgSrc' => 'landscape (8).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 9, 'imgSrc' => 'landscape (9).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 9, 'imgSrc' => 'landscape (10).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 9, 'imgSrc' => 'landscape (11).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 10, 'imgSrc' => 'landscape (12).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 10, 'imgSrc' => 'landscape (13).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 10, 'imgSrc' => 'landscape (14).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 11, 'imgSrc' => 'landscape (15).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 11, 'imgSrc' => 'landscape (16).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 11, 'imgSrc' => 'landscape (1).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 12, 'imgSrc' => 'landscape (2).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 12, 'imgSrc' => 'landscape (3).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 12, 'imgSrc' => 'landscape (4).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 13, 'imgSrc' => 'landscape (5).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 13, 'imgSrc' => 'landscape (6).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 13, 'imgSrc' => 'landscape (7).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 14, 'imgSrc' => 'landscape (8).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 14, 'imgSrc' => 'landscape (9).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 14, 'imgSrc' => 'landscape (10).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 15, 'imgSrc' => 'landscape (11).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 15, 'imgSrc' => 'landscape (12).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 15, 'imgSrc' => 'landscape (13).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 16, 'imgSrc' => 'landscape (14).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 16, 'imgSrc' => 'landscape (15).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 16, 'imgSrc' => 'landscape (16).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 17, 'imgSrc' => 'landscape (1).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 17, 'imgSrc' => 'landscape (2).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 17, 'imgSrc' => 'landscape (3).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 18, 'imgSrc' => 'landscape (4).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 18, 'imgSrc' => 'landscape (5).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 18, 'imgSrc' => 'landscape (6).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 19, 'imgSrc' => 'landscape (7).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 19, 'imgSrc' => 'landscape (8).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 19, 'imgSrc' => 'landscape (9).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 20, 'imgSrc' => 'landscape (10).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 20, 'imgSrc' => 'landscape (11).jpg', 'created_at' => now(), 'updated_at' => now()],
            ['viewsId' => 20, 'imgSrc' => 'landscape (12).jpg', 'created_at' => now(), 'updated_at' => now()],
        ]);

        // 批量寫入 25 筆美食資料
        Views::insert([
            [
                'name' => '阿宗麵線',
                'city' => '臺北市',
                'town' => '萬華區',
                'address' => '峨眉街8-1號',
                'typeId' => 1,
                'brief' => '西門町經典老字號大腸麵線，排隊人潮絡繹不絕。',
                'content' => '阿宗麵線創立於1975年，是台北西門町最具代表性的平民美食之一。店家數十年來堅持選用優質手工麵線，搭配精心滷製的香Q大腸，並以柴魚精心熬煮出濃郁鮮美的湯頭。高湯口感滑順且帶有淡淡柴魚香氣，大腸處理得極為乾淨，入口軟嫩無異味且入味十足。這裡最大的特色之一就是沒有設置座位，國內外觀光客與在地民眾總是人手一碗捧在手心，站在店門口的步行街上當場品嚐，形成西門町獨特又熱鬧的街頭美食風景。享用時強烈建議加上店家特製的辣椒醬、蒜泥與烏醋，能讓整碗麵線的風味層次更加提升，令人回味無窮。',
                'tel' => '02-23888808',
                'like' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '阿宗麵線',
                'city' => '臺北市',
                'town' => '萬華區',
                'address' => '峨眉街8-1號',
                'typeId' => 6,
                'brief' => '西門町經典老字號大腸麵線，排隊人潮絡繹不絕。',
                'content' => '走進熱鬧的西門町商圈，遠遠就能看到阿宗麵線門口聚集著長長的排隊人潮。店內僅專注販售「大腸麵線」單一品項，分為大碗與小碗兩種選擇。店員舀麵線的手勢俐落快速，淋上高湯、加入大腸並撒上香菜，過程一氣呵成。熱氣騰騰的麵線濃稠度適中，麵線久煮不爛仍保有彈性，吸飽了柴魚高湯的甘甜。店家特製的三寶調味料：蒜醬、辣醬與烏醋，可依個人口味自行加料調味。無論是炎夏或寒冬，每天都有來自世界各地的遊客專程造訪，享受這種站著吃麵線的在地文化，是體驗台北傳統小味不可錯過的地標級店家。',
                'tel' => '02-23888808',
                'like' => 120,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '陽明山國家公園',
                'city' => '臺北市',
                'town' => '北投區',
                'address' => '竹子湖路1-20號',
                'typeId' => 1,
                'brief' => '四季皆有不同美景的台北後花園，以火山地質與花季聞名。',
                'content' => '陽明山國家公園距離台北市中心僅需短暫車程，是台北市民與遊客親近大自然的後花園。公園內擁有豐富且獨特的後火山地質景觀，如小油坑終年噴發的硫磺噴氣孔、冷水坑的天然溫泉，以及擎天崗那片廣袤遼闊的高山草原，常能看見水牛群漫步其間。陽明山一年四季皆呈現不同的迷人風貌，春季的陽明山花季迎來櫻花與杜鵑盛開，隨後竹子湖的海海芋與繡球花季接力綻放；夏季氣候涼爽宜人，是絕佳的避暑勝地；秋季滿山芒花隨風搖曳交織成金黃花海；冬季則有機會在強烈冷氣團來襲時欣賞山頭降雪。園區內規劃多條完善的健行步道，如七星山主峰步道與天母古道，兼具自然生態保育與休閒休閒功能。',
                'tel' => '02-28613601',
                'like' => 310,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '九份老街',
                'city' => '新北市',
                'town' => '瑞芳區',
                'address' => '基山街',
                'typeId' => 4,
                'brief' => '充滿懷舊山城風情與紅燈籠街景的知名歷史老街。',
                'content' => '九份老街座落於新北市瑞芳區的山坡上，早期因採金礦而繁華一時，後因礦盡人散而歸於平靜。直到電影《悲情城市》在此取景，加上其獨特山城風貌與日本動畫《千與千尋》場景的神似，讓這座小鎮重新煥發光彩，成為享譽國際的知名觀光勝地。老街主要由基山街、豎崎路與輕便路貫穿，狹窄的階梯巷弄依山而建，兩旁懸掛著古色古香的紅燈籠，夕陽西下點燈時分，景緻格外詩情畫意。漫步於老街，不僅能品嚐 Q 彈有勁的阿柑姨芋圓、傳統草仔粿與香濃芋仔冰等在地古早味小吃，還能找間景觀茶樓品茗，遠眺基隆嶼與綿延的海岸線，感受濃濃的懷舊人文氣息。',
                'tel' => '02-24063270',
                'like' => 285,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '野柳地質公園',
                'city' => '新北市',
                'town' => '萬里區',
                'address' => '港東路167-1號',
                'typeId' => 1,
                'brief' => '大自然鬼斧神工，享譽國際的女王頭奇岩地貌。',
                'content' => '野柳地質公園位於新北市萬里區，突出的岬角長達1,700公尺，是大自然歷經數百萬年鬼斧神工打造的天然地質博物館。因波浪侵蝕、地殼運動與風化作用的共同影響，造就了許多造形奇特且令人驚嘆的岩石地景。其中最具代表性的當屬享譽國際的「女王頭」，其盤髮脖頸的高貴姿態維妙維肖，是遊客爭相拍照打卡的焦點。除此之外，園區內還有蕈狀岩、蜂窩岩、豆腐岩、燭台岩與仙女鞋等豐富的地質奇觀。沿著園區設置完善步道漫步，不僅能近距離觀察海蝕平台與海水沖蝕出的奇岩怪石，更能深刻體驗地質演化的奧妙與大自然的滄海桑田，是兼具生態教育與觀光價值的世界級景點。',
                'tel' => '02-24922016',
                'like' => 195,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '淡水漁人碼頭',
                'city' => '新北市',
                'town' => '淡水區',
                'address' => '觀海路199號',
                'typeId' => 3,
                'brief' => '觀賞夕陽沉海絕佳地點，情人橋橫跨港區極具浪漫氛圍。',
                'content' => '淡水漁人碼頭位於淡水河出海口東岸，是一個兼具漁業功能與現代化休閒娛樂的知名休閒港區。這裡最引人注目的地標便是純白色的「情人橋」，這座跨港大橋造型宛如風帆，夜間會打上絢麗奪目的七彩光雕，極具浪漫情調。碼頭旁設有一條長達數百公尺的木棧道，是親友散步與情侶約會熱門場所。每當傍晚時分，天空漸漸染上金黃與霞紅交織的色彩，夕陽緩緩沉入大海的絕美畫面，被譽為淡水八景之一。港區內設施豐富，包含淡水人魚碼頭福容大飯店、情人塔觀景台，以及許多提供新鮮海鮮與咖啡特調的景觀餐廳，假日更常辦音樂會與文創市集，呈現悠閒浪漫的港灣風情。',
                'tel' => '02-28058401',
                'like' => 220,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '宮原眼科',
                'city' => '臺中市',
                'town' => '中區',
                'address' => '中山路20號',
                'typeId' => 6,
                'brief' => '日治時期眼科醫院改建，哈利波特霍格華茲風格復古建築。',
                'content' => '宮原眼科原為日治時期宮原武熊醫師於1927年開辦的眼科醫院，歷經歲月洗禮與結構損壞後，由日出集團接手進行老屋翻新與老建築活化。團隊保留了外觀紅磚牆與舊牌樓，並在內部注入驚豔的現代設計元素。走進大廳，高聳直達天花板的木製書架、挑高透光的玻璃天井與古典雕花裝飾，營造出宛如哈利波特電影中霍格華茲魔法學校的奇幻震撼視覺。這裡專賣口味多達數十種的獨家冰淇淋，包含多款台灣茶葉、新鮮水果與巧克力系列，並能搭配土鳳梨酥、乳酪蛋糕等澎湃配料。此外，店內販售的鳳梨酥、牛軋糖與花餅等伴手禮包裝精美精緻，充滿復古文創質感，是台中最紅的必訪地標。',
                'tel' => '04-22271927',
                'like' => 260,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '高美濕地',
                'city' => '臺中市',
                'town' => '清水區',
                'address' => '美堤街',
                'typeId' => 1,
                'brief' => '被譽為台灣版天空之鏡，擁有絕美的夕陽與風車景致。',
                'content' => '高美濕地（高美野生動物保護區）位於台中清水大甲溪出海口南側，面積廣達701.3公頃，擁有豐富的泥灘地與潮間帶生態環境。這裡曾被外媒讚譽為「台灣版天空之鏡」，每當退潮時，平靜無波的水面反射出湛藍天空與朵朵白雲，夢幻景致令人屏息。園區建有長達百公尺的木棧道，讓遊客能在不破壞濕地生態的前提下走入潮間帶，親近觀察彈塗魚、招潮蟹等豐富生物，更是冬季節候鳥遷徙的重要棲息地。到了清晨與傍晚，夕陽西下將天空染成金橙紫紅交織的漸層色澤，搭配背景一整排矗立的大型風力發風車，構成一幅自然與科技和諧交融的絕美畫卷。',
                'tel' => '04-26565810',
                'like' => 340,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '日月潭國家風景區',
                'city' => '南投縣',
                'town' => '魚池鄉',
                'address' => '中山路599號',
                'typeId' => 3,
                'brief' => '台灣最大半天然淡水湖泊，提供環湖單車與纜車體驗。',
                'content' => '日月潭位於南投縣魚池鄉，為台灣最具代表性的高山湖泊風景區。湖泊以拉魯島為界，東側形如日輪，西側狀如彎月，因而得名「日月潭」。湖水清澈碧綠，四季群山環抱，晨昏煙波浩渺，景色變化萬千。旅遊日月潭的方式極為多樣，可搭乘綠能遊艇穿梭於水社碼頭、玄光寺與伊達邵碼頭之間，品嚐著名的阿婆香菇茶葉蛋；或乘坐日月潭纜車俯瞰湖光山色並直達九族文化村。值得一提的是，日月潭環湖自行車道曾被美國 CNN 評選為全球十條最美自行車道之一，騎著單車平緩漫遊於水上步道，享受微風拂面，是極致舒心的人生享受。',
                'tel' => '049-2855668',
                'like' => 410,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '清境農場',
                'city' => '南投縣',
                'town' => '仁愛鄉',
                'address' => '仁和路170號',
                'typeId' => 3,
                'brief' => '海拔1750公尺的高山青青草原，人氣綿羊秀精彩有趣。',
                'content' => '清境農場座落於南投縣仁愛鄉，海拔約1,750公尺，空氣清新、氣候涼爽宜人，素有「台灣小瑞士」的美譽。農場內最受歡迎的區域是廣袤綿延的「青青草原」，湛藍天空下綠草如茵，四周圍繞著合歡山與奇萊山等雄偉群峰。遊客可以漫步於草原上，與成群溫順可愛的柯利代綿羊親密互動、餵食與合影。假日舉辦的「綿羊秀」更是不容錯過的經典節目，由專業紐西蘭牧羊人帶來精彩的牧羊犬趕羊與剪羊毛表演，過程妙趣橫生；此外還有展現高超騎術的「馬術秀」。結合清境高空觀景步道與小瑞士花園，讓人在高山間感受宛如歐洲牧場般的愜意風情。',
                'tel' => '049-2802172',
                'like' => 380,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '鹿港老街',
                'city' => '彰化縣',
                'town' => '鹿港鎮',
                'address' => '埔頭街',
                'typeId' => 4,
                'brief' => '一府二鹿三艋舺，保存完善的清代閩南傳統紅磚建築街區。',
                'content' => '清代台灣有「一府二鹿三艋舺」的諺語，道出了彰化鹿港繁華一時的歷史地位。如今的鹿港老街（主要包含埔頭街、瑤林街與大有街），已被指定為古蹟保存區，是台灣保存最為完整的清代傳統閩南式紅磚建築街區。漫步在曲折狹窄古樸的紅磚道上，兩旁盡是門楣雕花、充滿歷史氣息的古厝門第，彷彿穿越時空重回百年前的港口繁華景象。老街周邊散落著眾多知名歷史古蹟與景點，如歷史悠久的鹿港天后宮、龍山寺、窄小的摸乳巷與九曲巷。老街內更匯聚了無數在地古早味小吃，如麵線糊、肉包、芋丸、牛舌餅與鳳眼糕，是結合歷史人文與美食饗宴的旅遊勝地。',
                'tel' => '04-7772006',
                'like' => 180,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '文章牛肉湯',
                'city' => '臺南市',
                'town' => '安平區',
                'address' => '安平路300號',
                'typeId' => 2,
                'brief' => '安平超人氣溫體牛肉湯，湯頭鮮甜牛肉嫩口。',
                'content' => '品嚐「溫體牛肉湯」是造訪台南不可或缺的道地美食體驗，而位於安平區的文章牛肉湯更是其中的超人氣代表。店家每日嚴選從善化屠宰場新鮮直送的本土溫體牛肉，憑藉主廚優異的手藝切出薄厚適中的牛肉片，再將以牛大骨、牛肉、中藥材及多種新鮮蔬菜長時間慢火熬煮的高湯直接沖入碗中。利用高湯的餘溫將牛肉瞬間燙至誘人的粉紅色澤，入口鮮嫩多汁，湯頭甘甜鮮美且毫無腥味。搭配店家特製的薑絲醬油膏，或是隨湯附贈的香濃牛肉燥飯，每一口都是道地的府城美味。無論是清晨早餐還是宵夜時分，店門口總是絡繹不絕，展現台南美食的無窮魅力。',
                'tel' => '06-2284626',
                'like' => 290,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '赤崁樓',
                'city' => '臺南市',
                'town' => '中西區',
                'address' => '民族路二段212號',
                'typeId' => 4,
                'brief' => '荷蘭時期興建之普羅民遮城，台南最具代表性的國定古蹟。',
                'content' => '赤崁樓位於台南市中西區，原為1653年荷蘭人所建的「普羅民遮城」（Fort Provintia），是台南市最具歷史意義與代表性的國定古蹟。數百年來，歷經明鄭時期、清領時期及日治時期的演變，原本的荷式城堡結構已多改改為漢式建築，形成了如今海神廟與文昌閣雙樓並立的典雅格局。庭園內最顯著的景觀，是九座清乾隆年間立於石龜背上的「御龜碑」，記載著平定林爽文事件的功績。園區內綠意盎然，古榕盤根錯節，典雅的紅瓦飛簷與綠釉朱欄交相輝映。到了夜晚，園區打上柔和燈光，沉靜古樸的氛圍更是別具浪漫韻味，是探索台南府城深厚歷史底蘊的必訪之地。',
                'tel' => '06-2205647',
                'like' => 210,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '奇美博物館',
                'city' => '臺南市',
                'town' => '仁德區',
                'address' => '文華路二段666號',
                'typeId' => 4,
                'brief' => '純白西洋宮殿式建築，收藏西洋藝術、樂器與兵器典藏。',
                'content' => '奇美博物館位於台南仁德區的台南都會公園內，是由奇美實業創辦人許文龍先生傾力打造的私立博物館。主建築採用宏偉的西洋古典宮殿風格，純白色的宏偉建築前設有氣勢磅礴的阿波羅噴泉與兩側豎立希臘神話神像的繆思廣場橋，讓人彷彿一秒穿越置身歐洲。館內展覽空間極為遼闊，典藏涵蓋西洋藝術、樂器、兵器、自然史及古文物等五大領域。其中，博物館擁有全球規模最大的小提琴收藏，並設有生動的動物標本展廳與震撼的西洋古兵器展區。豐富珍貴的展品結合高規格的國際級展演空間，兼具知性美感與藝術饗宴，是全台灣極富盛名的藝術文化地標。',
                'tel' => '06-2660808',
                'like' => 360,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '駁二藝術特區',
                'city' => '高雄市',
                'town' => '鹽埕區',
                'address' => '大勇路1號',
                'typeId' => 3,
                'brief' => '舊港口倉庫改建，結合文創展覽、裝置藝術與輕軌的藝術園區。',
                'content' => '駁二藝術特區座落於高雄港第三船渠內，原為建於1970年代的港口舊廢棄倉庫群。「駁二」意指第二接駁碼頭，經高雄市政府與藝術家團隊共同規劃活化後，如今已翻轉成為台灣最具代表性的跨界藝術創作與文創聚落。園區主要分為大勇倉庫、蓬萊倉庫與大義倉庫三大區域，廣大的戶外空間陳列著豐富多彩的巨型公仔、大型裝置藝術與塗鴉壁畫。這裡常年舉辦多元前衛的當代藝術展覽、音樂祭與手作文創市集，並有許多特色獨立書店、手作工坊與景觀餐廳進駐。配合高雄輕軌貫穿園區，以及鄰近的高雄流行音樂中心與大港橋，展現高雄港灣城市的雄厚文化活力。',
                'tel' => '07-5214899',
                'like' => 330,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '墾丁國家公園',
                'city' => '屏東縣',
                'town' => '恆春鎮',
                'address' => '墾丁路596號',
                'typeId' => 5,
                'brief' => '台灣熱帶度假勝地，擁有珊瑚礁海岸與水上活動樂園。',
                'content' => '墾丁國家公園位於台灣本島最南端的恆春半島，為台灣第一座國家公園，也是享譽盛名的熱帶度假勝地。園區三面環海（東臨太平洋、西西接台灣海峽、南面巴士海峽），擁有極其獨特且豐富的珊瑚礁地形與熱帶森林生態。這裡擁有多處令人流連忘返的自然景點，包含台灣本島最南端的鵝鑾鼻燈塔、擁有一線天地形的墾丁森林遊樂區、矗立海岸的船帆石與貓鼻頭公園。對於水上活動愛好者來說，南灣、白砂灣與小灣更是衝浪、潛水、浮潛與水上摩托車的天堂。到了夜晚，墾丁大街更會化身為熱鬧不夜城，各式泰式料理、調酒酒吧與在地小吃雲集，感受充滿南國熱情的渡假氛圍。',
                'tel' => '08-8861321',
                'like' => 450,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '太魯閣國家公園',
                'city' => '花蓮縣',
                'town' => '秀林鄉',
                'address' => '富世291號',
                'typeId' => 5,
                'brief' => '雄偉壯麗的大理石峽谷景觀，世界級的自然奇景。',
                'content' => '太魯閣國家公園以其雄偉壯麗、近乎垂直的大理石峽谷景觀聞名於世，是台灣最具國際聲譽的世界級自然奇景之一。立霧溪經過數百萬年不斷地向下侵蝕與切割，貫穿隆起的大理石岩層，形成了地勢高聳絕壁千仞的峽谷景貌。園區內著名景點無數，如燕子口步道能近距離觀賞地質紋理與燕子築巢奇觀、九曲洞步道感受大自然的幽深曲折、長春祠感念開闢中橫公路的榮民，以及聳立於高山間的砂卡噹步道與白楊步道。走在峭壁間的步道上，一側是千尺高崖，另一側是奔騰急湍的碧綠溪水，令人不禁讚嘆大自然的鬼斧神工與磅礡氣勢。',
                'tel' => '03-8621100',
                'like' => 490,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '佳興冰果室',
                'city' => '花蓮縣',
                'town' => '新城鄉',
                'address' => '博愛路22號',
                'typeId' => 6,
                'brief' => '新城老街懷舊冰果室，以全檸檬連皮打製的招牌檸檬汁聞名。',
                'content' => '佳興冰果室座落於花蓮新城老街上，是一間擁有超過六十年歷史的懷舊冰果室，也是前往太魯閣或七星潭途中的必訪美食據點。這裡最享譽盛名的鎮店之寶就是「招牌檸檬汁」，與一般壓榨汁不同，店家選用整顆屏東優質檸檬，連同外皮一同榨汁，並獨家加入煉乳進行調和。這項創舉成功抑制了檸檬皮的苦澀味，反而帶出滑順香醇的口感，酸甜平衡且極度清涼解渴，即便是不敢喝酸的人也能一口接一口。除了檸檬汁與檸檬棒棒冰外，店家附設的小吃部亦聲名遠播，其澎湃豪邁的什錦炒麵、快炒小菜與酸菜大腸，更是深受在地人與饕客喜愛的澎湃傳統美味。',
                'tel' => '03-8611888',
                'like' => 165,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '七星潭海岸風景區',
                'city' => '花蓮縣',
                'town' => '新城鄉',
                'address' => '海岸路',
                'typeId' => 1,
                'brief' => '優美的新月形礫石海灣，聽海浪淘洗鵝卵石聲極度療癒。',
                'content' => '七星潭（月牙灣）位於花蓮縣新城鄉，是一個呈現優美弧線的新月形礫石海灣。雖然名為「潭」，但實際上是緊鄰浩瀚太平洋的湛藍海灣。這裡的海岸線並非細沙，而是由無數被海浪千錘百鍊沖刷得圓潤流暢的晶瑩鵝卵石所組成。坐在海灘上，看著蔚藍的海浪一波波湧上岸，聽著海浪退去時淘洗鵝卵石發出的「沙沙」聲響，過程極度療癒身心。七星潭沿線設有完善的濱海自行車道、賞景步道與觀景亭，遠處可遙望雄偉的清水斷崖。清晨是觀賞太平洋日出的絕佳聖地，夜晚則因無光害干擾，成為聽濤觀星的浪漫景點。需要特別注意的是，七星潭屬於陡降型海岸，海浪暗湧危險，切勿冒險下水游泳。',
                'tel' => '03-8221530',
                'like' => 370,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '伯朗大道',
                'city' => '臺東縣',
                'town' => '池上鄉',
                'address' => '錦新三號道路',
                'typeId' => 1,
                'brief' => '翠綠稻浪包圍的夢幻田園大道，金城武樹熱門打卡點。',
                'content' => '伯朗大道位於台東縣池上鄉，是一條廣受矚目的田園鄉間小路。這條道路之所以一砲而紅，源於伯朗咖啡與巨星金城武曾在此拍攝廣告。這條小路最大的特色在於兩旁盡是廣袤綿延無邊際的池上稻田，且整條道路完全沒有任何一支電線桿，視野無比遼闊純淨。隨四季更迭呈現出截然不同的純粹風貌：每年五至六月與十至十一月稻穗成熟之際，整片大地鋪上一層耀眼奪目的金黃色金黃稻浪；而在播種初期，水田則如鏡面般反射著藍天白雲與遠方中央山脈的倒影。遊客可租乘單車或電動自行車漫遊其間，拜訪知名的「金城武樹」與「框景裝置藝術」，體驗花東縱谷的慢活步調。',
                'tel' => '089-862041',
                'like' => 420,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '三仙臺風景區',
                'city' => '臺東縣',
                'town' => '成功鎮',
                'address' => '基翬路74號',
                'typeId' => 1,
                'brief' => '離岸小島與經典八拱跨海步橋，東海岸看曙光首選聖地。',
                'content' => '三仙臺位於台東縣成功鎮東北方，是由強烈海水侵蝕斷裂而形成的離岸小島。民間傳說呂洞賓、鐵拐李與何仙姑三位仙人曾登島留下足跡，因而得名「三仙臺」。園區最醒目的地標是建於1987年的「八拱跨海步橋」，這座造型如長龍波浪起伏的紅灰色彩虹大橋，優美地橫跨於湛藍大海之上，將本島與離岸島連接起來。島上地形豐富，包含海蝕溝、壺穴與海蝕柱等自然奇景，並設有環島步道與台灣最早的燈塔。三仙臺更是全台灣每年元旦迎第一道曙光的熱門首選聖地，當金黃晨曦穿透雲層撒在跨海大橋與海面上，壯麗非凡的畫面令人動容。',
                'tel' => '089-854000',
                'like' => 310,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '無名台南碗粿',
                'city' => '臺南市',
                'town' => '中西區',
                'address' => '國華街三段',
                'typeId' => 6,
                'brief' => '傳統手工古早味碗粿。',
                'content' => '位於台南美食戰場國華街的「無名台南碗粿」，是許多在地老台南人從小吃到大的私房口袋名單。店家數十年來堅持遵循傳統工法，嚴選存放一段時間的老米磨成米漿，確保製作出的碗粿Q彈有扎實口感。內餡用料毫不吝嗇，包入紅燒香菇、溫體豬肉塊、鹹蛋黃與紅蔥頭，蒸煮出來的碗粿色澤呈現深沉誘人的琥珀色。享用時，以傳統竹篾划開碗粿切成十字，淋上店家靈魂所在、甘甜鹹香的特製蒜蓉醬油膏與蒜泥，一口咬下米香與肉香在口中完美爆發。配上一碗清爽鮮甜的魚羹湯，就是最道地、最富人間煙火氣的府城古早味早餐。',
                'tel' => '06-2220000',
                'like' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '宮原眼科冰淇淋',
                'city' => '臺中市',
                'town' => '中區',
                'address' => '中山路20號',
                'typeId' => 2,
                'brief' => '由日治時期眼科診所改建的復古冰淇淋與伴手禮專賣店。',
                'content' => '宮原眼科冰淇淋是台中紅遍國內外的旗艦級甜點體驗。這座由舊眼科診所歷史建築活化重生的空間，除了其宛如霍格華茲魔法城堡般的挑高空間吸引無數眼球外，其冰淇淋專賣區更是人潮排隊的焦點。店內提供超過五十種獨家研發的冰淇淋口味，細分為四大系列：包含選用台灣鹿谷烏龍、東方美人等高山茶葉的「茶系列」；嚴選各國產區與可可濃度的「巧克力系列」；展現台灣在地水果鮮甜的「水果系列」；以及靈感來自傳統甜點的「特調系列」。點餐時更能免費挑選澎湃的配料，如一整顆日出土鳳梨酥、花餅、乳酪蛋糕與手工餅乾，組合成視覺與味覺雙重享受的豪華冰淇淋聖代。',
                'tel' => '04-22271927',
                'like' => 85,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '文章牛肉湯',
                'city' => '臺南市',
                'town' => '安平區',
                'address' => '安平路300號',
                'typeId' => 1,
                'brief' => '安平必吃溫體牛肉湯，鮮甜甘美。',
                'content' => '提到台南安平的人氣美食，文章牛肉湯絕對是榜上有名的標竿店家。店家之所以長年深受饕客推崇，關鍵在於對食材新鮮度的絕對堅持。每日清晨與下午兩次從善化屠宰場直送最新鮮的本土溫體牛肉，未經冷凍的牛肉保有了最佳的肉質水分與軟嫩口感。店家以牛骨、牛雜與數種新鮮蔬菜慢火熬製出高雅清甜的高湯，當滾燙的清湯淋在鮮切牛肉片上，瞬間將牛肉熟化至五至七分的完美狀態。湯頭散發著牛肉特有的鮮美甜味，肉質軟嫩帶點微Q彈性。內用點選牛肉湯還可享用香氣四溢的牛肉燥飯，濃郁鹹香的牛肉燥搭配白飯，令人胃口大開。',
                'tel' => '06-2284626',
                'like' => 250,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => '佳興冰果室',
                'city' => '花蓮縣',
                'town' => '新城鄉',
                'address' => '博愛路22號',
                'typeId' => 6,
                'brief' => '新城老街懷舊冰果室，招牌檸檬汁。',
                'content' => '位於花蓮新城老街上的佳興冰果室，是一間充滿濃厚歲月痕跡與古早味氣息的六十年老店。店內最馳名的鎮店之寶「佳興檸檬汁」，風靡全台並成為許多人造訪花蓮必買的伴手禮。與一般榨汁方式不同，店家堅持使用整顆新鮮檸檬連皮帶肉切塊，加入特製煉乳一同打碎調配。煉乳的濃郁奶香巧妙地壓制了檸檬皮原有的苦澀味，同時保留了檸檬極致的清香與天然果酸，打造出酸甜順口、乳白滑順的完美風味，冰鎮後享用更是消暑解膩。除了冰品飲料外，店內的小吃部更提供份量澎湃的在地傳統熱炒，如古早味什錦炒麵、炒蛤蜊與滷味拼盤，是遊客享受東海岸美食的熱門景點。',
                'tel' => '03-8611888',
                'like' => 45,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
        $this->call([
            ManagerSeeder::class,
            MemberSeeder::class,
            WishlistSeeder::class
        ]);
    }
}
